openapi: 3.0.3
info:
  title: Swagger Transaction - OpenAPI 3.0
  version: 1.0.11

tags:
  - name: transaction
    description: Everything about your transaction
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /transactions:
    get:
      tags:
        - transaction
      summary: Find transaction by token
      description: Find all the transaction corresponding to one token
      operationId: findTransactionByToken
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          explode: true
          schema:
            enum:
              - Authorization -Attach Bearer JWT token
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transactions'
        '400':
          description: Invalid token supplied
        '500':
          description: Internal Server Error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /transaction/{transactionId}:
    get:
      tags:
        - transaction
      summary: Find transaction by Id
      description: Find a transaction by his transactionId
      parameters:
        - name: transactionId 
          in: path
          description: ID of transaction to return
          required: true
          schema:
            type: integer
            format: int64
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          explode: true
          schema:
            enum:
              - Authorization -Attach Bearer JWT token
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Transactions'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transactions'
        '400':
          description: Invalid token supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
    put:
      tags:
        - transaction
      summary: Update a transaction
      description: Update an information of an existing transaction
      operationId: updateInfoTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction to return
          required: true
          schema:
            type: integer
            format: int64
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          explode: true
          schema:
            enum:
              - Authorization -Attach Bearer JWT token
      requestBody:
        description: Update an existent transaction in the account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transactions'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          description: Invalid ID supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
      security:
        - api_key: []
        - petstore_auth:
            - write:pets
            - read:pets
    post:
      tags:
        - transaction
      summary: Add a transaction
      description: Add a new information of a transaction
      operationId: addInfoTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          explode: true
          schema:
            enum:
              - Authorization -Attach Bearer JWT token
      responses:
        '405':
          description: Invalid input
        '500':
          description: Internal Server Error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
    delete:
      tags:
        - transaction
      summary: Delete a transaction
      description: Delete an information of a transaction
      operationId: deleteInfoTransaction
      parameters:
        - name: transactionId
          in: path
          description: ID of transaction that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          explode: true
          schema:
            enum:
              - Authorization -Attach Bearer JWT token
      responses:
        '400':
          description: Invalid Id supplied
        '500':
          description: Internal Server Error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  
components:
  schemas:
    Transactions:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 15489
        Date:
          type: integer
          format: int64
          example: 20/12/2022
        Amount:
          type: integer
          format: int64
          example: $2,082.79
        Name:
          type: integer
          format: int64
          example: Argent Bank Checking (x8349)
        Balance:
          type: integer
          format: int64
          example: Available
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header